name: "Terraform"
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: checkout checkov compositeAction
        uses: actions/checkout@v3
        with:
          repository: ppratheesh/terraform-exercise
          path: ./terraform-exercise
        
      - name: run checkov scan against plan
        uses: ./terraform-exercise/.github/actions/release
        with:
          RELEASE_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
