name: "Terraform"
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Release
        uses: K-Phoen/semver-release-action@master
        with: 
         release_branch: main
