name: "Terraform"
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
  push: 
    branches:
      - 'main'
defaults:
      run:
        shell: bash
    
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      current-dir: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: checkout release workflow
        uses: actions/checkout@v3
        with:
          repository: ppratheesh/github-shared-workflows
          path: ./github-shared-workflows
          
      - name: checing folder
        run: |
          ls
          pwd
          
      - name: release action
        uses: ./github-shared-workflows/github-shared-workflows/.github/actions/release
        with:
          RELEASE_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
