name: "Terraform"
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
  push: 
    branches:
      - 'main'
defaults:
      run:
        shell: bash
    
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      current-dir: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: checkout release workflow
        uses: actions/checkout@v3
        with:
          repository: infracloudio/github-shared-workflows
          path: ./github-shared-workflows
          
      - name: checing folder
        run: |
          ls
          pwd
          echo "inided folder"
          ls -la github-shared-workflows
          echo "cd into ./github-shared-workflows/.github/actions/release/"
         # cd ./github-shared-workflows/.github/actions/release/
          echo "printing pwd"
          pwd
          ls -la
          
      - name: release action
        uses: ./github-shared-workflows/.github/actions/checkov
        with:
          RELEASE_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
